### ISSUE TITLE
关于LLPAUC函数中参数的由来

### ISSUE THREAD

**Issue by KokonaShiki** [swt-user/LLPAUC#1]
论文作者您好，我在阅读论文的时候尝试理解您的代码，我注意到定义了LLPAUC的代码段中有
a=torch.clip(a,0,1)
b=torch.clip(b,0,1)
gamma=torch.clip(gamma,-1,1)
theta_a=torch.clip(theta_a,0,1e9)
theta_b=torch.clip(theta_b,0,1e9)
sp = torch.clip(sp, -1, 4)
sn=torch.clip(sn,0,5)
如上压缩代码，但我并没有找到定义这些参数的代码段在哪里，forward类中这些参数的取值都设为了none，所以显然不是在loss.py的文件中，我尝试溯源寻找但并没有成功，如果您能拨冗回答我的问题，我将不胜感激

**Comment by swt-user** [comment]
Thanks for your interest!

You could refer to the code in ``/recbole/model/general_recommender/bpr_tp_point.py''.

**Comment by KokonaShiki** [comment]
感谢您的解答，祝您科研顺利，生活愉快
